# Generated by Django 3.2 on 2021-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postIt', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
