# Generated by Django 3.2 on 2021-04-28 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postIt', '0005_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='site_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
