# Generated by Django 3.2 on 2021-04-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postIt', '0008_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
