# Generated by Django 3.2.2 on 2021-05-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postIt', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourite',
            field=models.BooleanField(default=True),
        ),
    ]
